# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='screenshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
